---
# Copyright (C) 2014-2019 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2019 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Create directory for gituser homes
  file:
    path: '{{ gitusers_default_home_prefix }}'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0751'

- include_tasks: groups_present.yml
- include_tasks: gitusers.yml
- include_tasks: git-shell.yml
#- include: forward.yml
- include_tasks: sshkeys.yml
- include_tasks: groups_absent.yml
