---
# vim: foldmarker=[[[,]]]:foldmethod=marker

# Copyright (C) 2015-2016 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015      Hartmut Goebel <h.goebel@crazy-compilers.com>
# Copyright (C) 2015-2019 Robin Schneider <ypid@riseup.net>
# Copyright (C) 2015-2019 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Import custom Ansible plugins
  import_role:
    name: 'ansible_plugins'

- name: Import DebOps global handlers
  import_role:
    name: 'global_handlers'

- name: Import DebOps secret role
  import_role:
    name: 'secret'

- include_tasks: 'system_package_management.yml'
  tags: [ 'role::owncloud:pkg' ]

- include_tasks: 'tarball.yml'
  when: (owncloud__variant in ["nextcloud"])
  tags: [ 'role::owncloud:tarball' ]

- include_tasks: 'setup_owncloud.yml'
  tags: [ 'role::owncloud:config' ]

- include_tasks: 'ldap.yml'
  when: (owncloud__ldap_enabled | bool)
  tags: [ 'role::owncloud:ldap' ]

- include_tasks: 'theme.yml'
  tags: [ 'role::owncloud:theme' ]

- include_tasks: 'copy.yml'
  tags: [ 'role::owncloud:copy' ]
